### ISSUE TITLE
Cannot set Domain scaling to None in GUI

### ISSUE THREAD

**Issue by wyrnat** [SLAC-ML/Badger#8]
If I once chose domain scaling (eg. sinusoid) it does not allow me to have no domain scaling anymore.
Only way out is to make a new routine.

**Comment by wenatuhs** [comment]
Hi @wyrnat, thanks for trying out Badger, it's actually OK to have the domain scaling on -- it applies the default option (semi-linear scaling) if you choose nothing anyway (this is to prevent setting the variables outside of their ranges by the algorithm, some algorithms are boundless, such as Simplex). But you are right this behavior could bring confusion, I'll try getting rid of the "no selection" options in the future release. Thanks for the feedback!

**Comment by wyrnat** [comment]
Hi Zhe, thanks for the info. I will close the issue then.
FYI: I will be more active in the future with Issues and pull request as we are now starting to use Badger more at XFEL

**Comment by wenatuhs** [comment]
That's great to know! Thanks for the updates on the XFEL side!
